all:
	g++ -std=c++11  Ejercicio1.cpp -o e1 -lpthread
	g++ -std=c++11  Ejercicio2.cpp -o e2 -lpthread
	g++ -std=c++11  Ejercicio3.cpp -o e3 -lpthread
	g++ -std=c++11  Ejercicio4.cpp -o e4 -lpthread
	g++ -std=c++11  Ejercicio5.cpp -o e5 -lpthread
	g++ -std=c++11  Ejercicio6.cpp -o e6 -lpthread
	g++ -std=c++11  Semaforo.cpp Ejercicio7.cpp -o e7 -lpthread