Programa5-2: Programa5-2.cpp PoligonoIrreg.o
	g++ Programa5-2.cpp PoligonoIrreg.o Coordenada.o -o p5
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
