Programa6-1: Programa6-1.cpp PoligonoIrreg.o
	g++ Programa6-1.cpp PoligonoIrreg.o Coordenada.o -o p6
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c